[FIX](CI): Refactor coding style check workflow by removing unnecessary steps and improving error annotation

diff --git a/.github/workflows/ci-mirror.yml b/.github/workflows/ci-mirror.yml
--- a/.github/workflows/ci-mirror.yml
+++ b/.github/workflows/ci-mirror.yml
@@ -25,22 +25,27 @@ jobs:
         run: make tests_run
 
   coding_style:
-    name: Coding Style Check
-    runs-on: ubuntu-latest
+    runs-on: "ubuntu-latest"
+    container:
+        image: "ghcr.io/epitech/coding-style-checker:latest"
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
+        -   name: "Check coding style"
+            run: "/usr/local/bin/check.sh $(pwd) $(pwd)"
 
-      - name: Create Reports Directory
-        run: mkdir -p reports
+        -   name: "Annotate coding-style errors"
+            run: |
+                status=0
+                while IFS= read -r line; do
+                    file=$(echo "${line}" | cut -d ':' -f1)
+                    pos=$(echo "${line}" | cut -d ':' -f2)
+                    type=$(echo "${line}" | cut -d ':' -f3)
+                    csid=$(echo "${line}" | cut -d ':' -f4)
 
-      - name: Download Coding Style Checker
-        run: |
-          curl -L https://raw.githubusercontent.com/Epitech/coding-style-checker/refs/heads/main/coding-style.sh -o coding-style.sh
-          chmod +x coding-style.sh
-
-      - name: Run Coding Style Checker
-        run: ./coding-style.sh . reports
+                    [[ "${type:1}" == "illegal"* ]] && continue
+                    echo "::error file=${file},line=${pos},title=${type:1} ${csid}::${type:1}: ${csid} at ${file}:${pos}"
+                    status=1
+                done < coding-style-reports.log
+                exit "${status}"
 
   mirror:
     name: Mirror to Epitech Repository
